// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnbN-thopCWaWMy3BvT7QJP-FnwoVp4v0',
    appId: '1:485958768252:web:df96e556bb9d12ab695bf9',
    messagingSenderId: '485958768252',
    projectId: 'firesotretest-f953c',
    authDomain: 'firesotretest-f953c.firebaseapp.com',
    storageBucket: 'firesotretest-f953c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQomiTBzxISGWpbmy6i9p7Q-Oq4-AgCUc',
    appId: '1:485958768252:android:c2f6ca71907de0cb695bf9',
    messagingSenderId: '485958768252',
    projectId: 'firesotretest-f953c',
    storageBucket: 'firesotretest-f953c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpuHFw4Ma1CeCs4PjUz4ybxmiCvM81pg',
    appId: '1:485958768252:ios:cddb61d623511034695bf9',
    messagingSenderId: '485958768252',
    projectId: 'firesotretest-f953c',
    storageBucket: 'firesotretest-f953c.appspot.com',
    iosClientId: '485958768252-dak0jutck3efb09abja3kc31rpq11uss.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtpuHFw4Ma1CeCs4PjUz4ybxmiCvM81pg',
    appId: '1:485958768252:ios:cddb61d623511034695bf9',
    messagingSenderId: '485958768252',
    projectId: 'firesotretest-f953c',
    storageBucket: 'firesotretest-f953c.appspot.com',
    iosClientId: '485958768252-dak0jutck3efb09abja3kc31rpq11uss.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
